/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#14d1ff',
        'primary-fixed-dim': '#d0bcff',
        'tertiary-container': '#fa5c1c',
        'tertiary-fixed-dim': '#ffb59c',
        primary: '#d0bcff',
        secondary: '#a6e6ff',
        'on-secondary-container': '#00566b',
        'inverse-on-surface': '#313030',
        'on-tertiary-fixed-variant': '#832700',
        surface: '#131313',
        'surface-dim': '#131313',
        'on-background': '#e5e2e1',
        'on-error': '#690005',
        'on-tertiary-container': '#511500',
        'on-tertiary-fixed': '#390c00',
        'error-container': '#93000a',
        outline: '#958ea0',
        'on-surface': '#e5e2e1',
        'surface-bright': '#3a3939',
        'on-primary': '#3c0091',
        'on-primary-container': '#340080',
        'on-primary-fixed-variant': '#5516be',
        'inverse-primary': '#6d3bd7',
        'on-secondary-fixed': '#001f28',
        'surface-tint': '#d0bcff',
        'on-secondary-fixed-variant': '#004e60',
        tertiary: '#ffb59c',
        'on-secondary': '#003543',
        'surface-container-high': '#2a2a2a',
        'outline-variant': '#494454',
        'on-surface-variant': '#cbc3d7',
        'tertiary-fixed': '#ffdbcf',
        'primary-fixed': '#e9ddff',
        'surface-container': '#201f1f',
        'on-tertiary': '#5c1900',
        'primary-container': '#a078ff',
        'secondary-fixed-dim': '#4cd6ff',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e2e1',
        'secondary-fixed': '#b7eaff',
        background: '#131313',
        error: '#ffb4ab',
        'on-primary-fixed': '#23005c',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Manrope'],
        label: ['Manrope'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}

